version: '3.8'

services:
  app:
    build: .
    container_name: chess_platform_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/chess_game_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=chess_distributed_prod_jwt_key_placement_2026
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: chess_platform_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: chess_platform_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
